Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

print(arr1 == arr2)
print(np.array_equal(arr1,arr2))

[[ True  True]
 [ True  True]]
True


Find the most frequent value and their indice(s) in the following arrays:
i.
x = np.array([1,2,3,4,5,1,2,1,1,1])
ii.
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
import numpy as np

def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_freq_values = values[counts == max_count]

    result_indices = {}
    for val in most_freq_values:
        result_indices[val] = np.where(arr == val)[0].tolist()

    return most_freq_values, result_indices

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

print(f"For x: {x}")
freq_x_values, freq_x_indices = most_frequent(x)
print(f"Most frequent value(s): {freq_x_values}, Indices: {freq_x_indices}")

print(f"\nFor y: {y}")
freq_y_values, freq_y_indices = most_frequent(y)
print(f"Most frequent value(s): {freq_y_values}, Indices: {freq_y_indices}")

For x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value(s): [1], Indices: {np.int64(1): [0, 5, 7, 8, 9]}

For y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value(s): [1 3], Indices: {np.int64(1): [0, 1, 2], np.int64(3): [4, 8, 9]}


For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
find i. Sum of all elements
ii.
iii.
Sum of all element’s row-wise
Sum of all element’s column-wise

In [ ]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

#i)sum of all elements
print(np.sum(gfg))

#ii)sum of elements row-wise
print(np.sum(gfg, axis=1))

#iii)sum of elements column-wise
print(np.sum(gfg, axis=0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]
